<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * Template Name:	Blog Home
* Description:		Blog Home
* @package			Tree Top Corp and CPG
* @author 			3rd Studio
* @link				http://www.3rdstudio.com/
* @copyright		Copyright (c) 2016, 3rd Studio, Inc.
* @license			Exclusively for Tree Top
 */

// Remove archive description
remove_action( 'genesis_before_loop', 'genesis_do_taxonomy_title_description', 15 );
// Add new archive description
add_action( 'genesis_before_content', 'tt_archive_description', 1);
function tt_archive_description() {
	?>
	<header class="entry-header">
		<div class="container">
			<div class="row">
				<div class="col-sm-9 col-sm-push-3">
					<?php echo genesis_do_taxonomy_title_description(); ?>
				</div>
			</div>
		</div>
	</header>
	<?php
}


add_action('genesis_before_loop', 'wpb_change_home_loop');
/*
 * Adding in our new home loop.
 */
function wpb_change_home_loop() {
	//if ( is_home() ) {

		/** Replace the home loop with our custom **/
		remove_action( 'genesis_loop', 'genesis_do_loop' );
		add_action( 'genesis_loop', 'wpb_custom_loop' );
		/** Custom  loop **/
		function wpb_custom_loop() {
		if ( have_posts() ) :
				do_action( 'genesis_before_while' );

				$arch_desc = get_the_archive_description();
				if ($arch_desc) {
					the_archive_description( '<div class="taxonomy-description">', '</div>' ); 
				} else {
					?>
						<div class="taxonomy-description">
							<p>
								<picture class="alignnone wp-image-3666 size-full">
									<source type="image/webp" srcset="/wp-content/uploads/2022/05/Crop-Blog-2.jpg.webp">
									<img src="/wp-content/uploads/2022/05/Crop-Blog-2.jpg" alt="" width="850" height="325">
								</picture>
							</p>
						</div>
					<?php
				}
				
				?>
				<div class="tting-blog-archive-wrap">
				<?php
				while ( have_posts() ) : the_post();
					do_action( 'genesis_before_entry' );
					
					printf( '<article %s>', genesis_attr( 'entry' ) );

						?>
						<div class="tting-blog-archive-article-img">
						<?php
						echo genesis_do_post_image(); //Add in featured image
						?>
						</div>
						<div class="tting-blog-archive-desc">
						<?php
						do_action( 'genesis_entry_header' );
						do_action( 'genesis_before_entry_content' );
						printf( '<div %s>', genesis_attr( 'entry-content' ) );
						
						//do_action( 'genesis_entry_content' ); //Remove standard excerpt
						
						
						
						echo the_excerpt_max_charlength(2000); //change amount of characters to display
						
						echo '</div>';
						do_action( 'genesis_after_entry_content' );
						do_action( 'genesis_entry_footer' );
						?>
						</div>
						<?php
					echo '</article>';
					
					do_action( 'genesis_after_entry' );
				endwhile; //* end of one post
				?>
				</div>
				<?php
				do_action( 'genesis_after_endwhile' );
			else : //* if no posts exist
				do_action( 'genesis_loop_else' );

			endif; //* end loop
		}
		add_action( 'genesis_sidebar', 'blog_home_sidebar' );
		function blog_home_sidebar() {
			genesis_widget_area( 'blog-cagetory-menu' );
		}
		
	//}
}
add_filter( 'genesis_attr_content', 'add_class_content' );
function add_class_content( $attributes ) {
 
	 // add original plus extra CSS classes
	 $attributes['class'] .= ' col-sm-9 col-sm-push-3';
	 
	 // return the attributes
	 return $attributes;
 
}
add_filter( 'genesis_attr_sidebar-primary', 'add_class_sidebar' );
function add_class_sidebar( $attributes ) {
 
	 // add original plus extra CSS classes
	 $attributes['class'] .= ' col-sm-3 col-sm-pull-9';
	 
	 // return the attributes
	 return $attributes;
 
}
// Add opening container and row divs
add_action('genesis_before_content', 'tt_opening_divs', 1);
function tt_opening_divs() {
	echo "<div class=\"container\">";
	echo "  <div class=\"row\">";
}
// Add closing container and row divs
add_action('genesis_after_content', 'tt_closing_divs', 50);
function tt_closing_divs() {
	echo "</div>";
	echo "  </div>";
}
/*
 * Limit the excerpt by character.
 *
 * @link Reference - http://codex.wordpress.org/Function_Reference/get_the_excerpt
 */
function the_excerpt_max_charlength($charlength) {
	$excerpt = get_the_excerpt();
	$charlength++;
	if ( mb_strlen( $excerpt ) > $charlength ) {
		$subex = mb_substr( $excerpt, 0, $charlength - 5 );
		$exwords = explode( ' ', $subex );
		$excut = - ( mb_strlen( $exwords[ count( $exwords ) - 1 ] ) );
		if ( $excut < 0 ) {
			echo mb_substr( $subex, 0, $excut );
		} else {
			echo $subex;
		}
		echo ' <br><a href="' . get_permalink() . '" class="more-link" title="Read More">Read More</a>';
	} else {
		echo $excerpt;
	}
}

unregister_sidebar( 'sidebar' );

genesis();