<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */

remove_action( 'genesis_loop', 'genesis_do_loop' );

//add_action( 'genesis_before_loop', 'genesis_do_search_title' );
/**
 * Echo the title with the search term.
 *
 * @since 1.9.0
 */



// Test function to get all children/grandchildren under /consumer/
/*function get_posts_children(){

    $posts = get_pages( array( 'post_status' => 'publish', 'child_of' => 16 ));

    //echo "# in posts: ".count($posts)."<br />";

    $posts = wp_list_pluck( $posts, 'ID' );
    return $posts;
}

$descendants = get_posts_children();

echo 'Array: <pre>';
print_r($descendants);
echo '</pre>';*/



/* Template Name: SearchWP Supplemental Search Results */
global $post;
// retrieve our search query if applicable
$query = isset( $_REQUEST['s'] ) ? sanitize_text_field( $_REQUEST['s'] ) : '';

// retrieve our pagination if applicable
$swppg = isset( $_REQUEST['swppg'] ) ? absint( $_REQUEST['swppg'] ) : 1;
if ( class_exists( 'SWP_Query' ) ) {

	$swp_query = new SWP_Query(
		// see all args at https://searchwp.com/docs/swp_query/
		array(
			's'      => $query,
			'page'   => $swppg,
		)
	);
	// set up pagination
	$pagination = paginate_links( array(
		'format'  => '?swppg=%#%',
		'current' => $swppg,
		'total'   => $swp_query->max_num_pages,
	) );
}

function be_custom_search_button_text( $text ) {
	return esc_attr( 'Go' );
}
add_filter('genesis_search_button_text', 'be_custom_search_button_text');


?>

	<section id="primary" class="content-area">
		<main id="main" class="site-main" role="main">

			<header class="entry-header">
				<div class="container">
					<div class="row">
						<div class="col-sm-12">
							<h1 class="entry-title" itemprop="headline">
								<?php if ( ! empty( $query ) ) : ?>
									<?php printf( __( 'Search Results for: %s', 'treetopcc-pro' ), $query ); ?>
								<?php else : ?>
									Search Tree Top
								<?php endif; ?>
							</h1>
						</div>
					</div>
				</div>
			</header>

			<div class="container">
				<div class="row">
					<div class="col-sm-12">
						<?php get_search_form(); ?>
					</div>
				</div>
			</div>

			<div class="container">
				<div class="row">
					<div class="col-sm-12 search-page-results">

						<?php if ( ! empty( $query ) && isset( $swp_query ) && ! empty( $swp_query->posts ) ) {
							foreach ( $swp_query->posts as $post ) {
								setup_postdata( $post );
								// output the result
								?>
									<div class="search-result">
										<h2>
											<a href="<?php echo get_permalink(); ?>">
												<?php the_title(); ?>
											</a>
											<!--<div class="excerpt"><?php the_excerpt(); ?></div>-->
										</h2>
									</div>
								<?php
							}
							
							wp_reset_postdata();
							// pagination
							if ( $swp_query->max_num_pages > 1 ) { ?>
								<div class="navigation pagination" role="navigation">
									<h2 class="screen-reader-text">Posts navigation</h2>
									<div class="nav-links">
										<?php echo wp_kses_post( $pagination ); ?>
									</div>
								</div>
							<?php }
						} else {
							?><p>No results found.</p><?php
						} ?>

					</div>
				</div>
			</div>

		</main><!-- .site-main -->
	</section><!-- .content-area -->

<?php 

genesis();
